id: PF08822E0
initial_creation_type: input
source_metadata:
  title: Tamdrin Gönpo Series
  language: en
  description: 'Texts by and about Tamdrin Gönpo (rta mgrin mgon po):'
  volume:
    c5e8de447f7441939666358c82fb7fc4:
      title: 'Bright Light of the Sun: A Simple Fire Offering Based on a Single Substance'
      parent: Practices
created_at: '2022-03-01T01:38:58.163316'
last_modified_at: '2022-03-01T01:38:58.163337'
